name: Release

on:
  push:
    branches: [main]
  pull_request:

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: 'https://npm.pkg.github.com'
          scope: '@datalens-tech'
          cache: npm
      - name: Install Packages
        run: npm ci
      - name: build
        run: npm run build
      - name: Git user configuration
        run: git config user.email "datalens-tech+bot@github.com" && git config user.name "Datalens-tech robot"
      - name: Publish
        run: npm version patch && npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
